### ISSUE TITLE
[BUG] Leak on heredoc with ctrl+c

### ISSUE THREAD

**Issue by PauloBastos96** [PauloBastos96/Minishell#50]
When doing ctrl+c in heredoc readline has a leak.

**Comment by Francisco-Zeferino** [comment]
I tested in my branch and doesn't crash, maybe we changed something that we shouldn't XD

**Comment by Francisco-Zeferino** [comment]
Tested with another person GNL and gave no leaks. The leak comes from GNL itself.

**Comment by PauloBastos96** [comment]
Fixed in 7a51ffa
